#!/usr/bin/env python3
"""
Build LaTeX report from local experiment analysis.

Reads the analysis markdown, converts to LaTeX with proper formatting,
embeds images, and compiles to PDF. Output lives in the pipeline's
local_results/{version}/ directory.

Two modes:
  1. Auto mode (default): Converts analysis.md → LaTeX → PDF using pandoc
  2. Agent mode: Spawns builder agent with reasoning to write custom LaTeX

Usage:
    python3 scripts/build_report.py <version>                     # Auto: pandoc MD→PDF
    python3 scripts/build_report.py <version> --agent             # Agent: builder writes LaTeX
    python3 scripts/build_report.py <version> --compile-only      # Just run pdflatex on existing .tex
    python3 scripts/build_report.py <version> --template custom   # Use custom LaTeX template
"""

import argparse
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

WORKSPACE = Path(os.environ.get('WORKSPACE', os.path.expanduser('~/.openclaw/workspace')))
ML_DIR = WORKSPACE / 'machinelearning' / 'snn_applied_finance'
RESULTS_BASE = ML_DIR / 'notebooks' / 'local_results'
SCRIPTS_DIR = WORKSPACE / 'scripts'
TEMPLATES_DIR = SCRIPTS_DIR / 'templates'

# LaTeX template for research reports
LATEX_TEMPLATE = r"""\documentclass[11pt,a4paper]{article}

% --- Packages ---
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage[margin=2.5cm]{geometry}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{float}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{caption}
\usepackage{subcaption}
\usepackage{amsmath}
\usepackage{enumitem}
\usepackage{listings}

% --- Pandoc compatibility ---
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% --- Unicode support ---
\DeclareUnicodeCharacter{03B1}{$\alpha$}
\DeclareUnicodeCharacter{03B2}{$\beta$}
\DeclareUnicodeCharacter{00B1}{$\pm$}
\DeclareUnicodeCharacter{2264}{$\leq$}
\DeclareUnicodeCharacter{2265}{$\geq$}

% --- Colors ---
\definecolor{linkcolor}{RGB}{0, 102, 204}
\definecolor{titlecolor}{RGB}{44, 62, 80}
\definecolor{sectioncolor}{RGB}{52, 73, 94}
\definecolor{codebackground}{RGB}{248, 248, 248}
\definecolor{codeborder}{RGB}{204, 204, 204}

% --- Hyperref ---
\hypersetup{
    colorlinks=true,
    linkcolor=linkcolor,
    urlcolor=linkcolor,
    citecolor=linkcolor,
    pdftitle={$title$},
    pdfauthor={Belam Research Pipeline},
}

% --- Headers/Footers ---
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small\textcolor{sectioncolor}{$title$}}
\fancyhead[R]{\small\textcolor{sectioncolor}{$date$}}
\fancyfoot[C]{\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}

% --- Section formatting ---
\titleformat{\section}
    {\large\bfseries\color{titlecolor}}
    {\thesection}{1em}{}
\titleformat{\subsection}
    {\normalsize\bfseries\color{sectioncolor}}
    {\thesubsection}{1em}{}
\titleformat{\subsubsection}
    {\normalsize\itshape\color{sectioncolor}}
    {\thesubsubsection}{1em}{}

% --- Code listings ---
\lstset{
    basicstyle=\ttfamily\small,
    backgroundcolor=\color{codebackground},
    frame=single,
    rulecolor=\color{codeborder},
    breaklines=true,
    breakatwhitespace=true,
    tabsize=4,
}

% --- Caption style ---
\captionsetup{
    font=small,
    labelfont=bf,
    format=plain,
    justification=centering,
}

% --- Image max width ---
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\makeatother
\let\oldincludegraphics\includegraphics
\renewcommand{\includegraphics}[2][]{%
    \oldincludegraphics[max width=\textwidth, #1]{#2}%
}

% --- Document ---
\begin{document}

% --- Title Page ---
\begin{titlepage}
\centering
\vspace*{3cm}
{\Huge\bfseries\color{titlecolor} $title$ \par}
\vspace{1cm}
{\Large\color{sectioncolor} Experiment Analysis Report \par}
\vspace{2cm}
{\large Pipeline: \texttt{$pipeline$} \par}
\vspace{0.5cm}
{\large $date$ \par}
\vspace{2cm}
{\normalsize
\begin{tabular}{rl}
\textbf{Experiments:} & $n_experiments$ \\
\textbf{Folds:} & $n_folds$ \\
\textbf{Total Runs:} & $total_runs$ \\
\textbf{Duration:} & $elapsed$ minutes \\
\textbf{Platform:} & Local CPU (ARM64, 4 cores) \\
\end{tabular}
}
\vfill
{\small Generated by Belam Research Pipeline \par}
\end{titlepage}

\tableofcontents
\newpage

$body$

\end{document}
"""


def get_results_dir(version: str) -> Path:
    """Find the results directory for a pipeline version."""
    versioned = RESULTS_BASE / version
    if versioned.exists():
        return versioned
    return RESULTS_BASE


def find_analysis_md(version: str, results_dir: Path) -> Path:
    """Find the analysis markdown file."""
    candidates = [
        results_dir / f'{version}_analysis.md',
        results_dir / 'analysis.md',
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def extract_frontmatter(md_path: Path) -> dict:
    """Extract YAML frontmatter from markdown file."""
    content = md_path.read_text()
    if not content.startswith('---'):
        return {}, content
    
    end = content.index('---', 3)
    fm_text = content[3:end].strip()
    body = content[end + 3:].strip()
    
    fm = {}
    for line in fm_text.split('\n'):
        if ':' in line:
            key, _, val = line.partition(':')
            fm[key.strip()] = val.strip().strip('"').strip("'")
    
    return fm, body


def build_with_pandoc(md_path: Path, output_pdf: Path, results_dir: Path,
                       template_path: Path = None) -> bool:
    """Convert MD → PDF using pandoc with our LaTeX template."""
    
    # Write our template
    if template_path is None:
        template_path = results_dir / 'report_template.tex'
    
    # Extract frontmatter for template variables
    fm, body = extract_frontmatter(md_path)
    
    # Write pandoc-compatible template
    # Pandoc uses $variable$ syntax which conflicts with LaTeX
    # So we write a pandoc template file
    pandoc_template = LATEX_TEMPLATE
    
    # Create a clean version of the MD without frontmatter for pandoc
    clean_md = results_dir / f'{md_path.stem}_clean.md'
    clean_md.write_text(body)
    
    template_path.write_text(pandoc_template)
    
    # Build pandoc command
    cmd = [
        'pandoc',
        str(clean_md),
        '-o', str(output_pdf),
        '--pdf-engine=pdflatex',
        f'--template={template_path}',
        f'--resource-path={results_dir}',
        '-V', f'title={fm.get("title", f"Experiment Analysis: {md_path.stem}")}',
        '-V', f'date={fm.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))}',
        '-V', f'pipeline={fm.get("pipeline", "unknown")}',
        '-V', f'n_experiments={fm.get("n_experiments", "?")}',
        '-V', f'n_folds={fm.get("n_folds", "?")}',
        '-V', f'total_runs={fm.get("total_runs", "?")}',
        '-V', f'elapsed={fm.get("elapsed_minutes", "?")}',
        '--highlight-style=tango',
        '--toc',
        '--number-sections',
    ]
    
    print(f"  📋 Running pandoc...")
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(results_dir))
    
    # Clean up temp files
    clean_md.unlink(missing_ok=True)
    
    if result.returncode != 0:
        print(f"  ❌ Pandoc failed:\n{result.stderr[:2000]}")
        return False
    
    return True


def build_with_pdflatex(tex_path: Path, output_dir: Path) -> bool:
    """Compile .tex → .pdf using pdflatex (2 passes for TOC)."""
    for pass_num in range(2):
        print(f"  📋 pdflatex pass {pass_num + 1}/2...")
        result = subprocess.run(
            ['pdflatex', '-interaction=nonstopmode', '-output-directory', str(output_dir), str(tex_path)],
            capture_output=True, text=True, cwd=str(output_dir),
            timeout=120,
        )
        if result.returncode != 0 and pass_num == 1:
            # Check if PDF was generated despite errors (common with Unicode warnings)
            pdf_name = tex_path.stem + '.pdf'
            pdf_candidate = output_dir / pdf_name
            if pdf_candidate.exists() and pdf_candidate.stat().st_size > 1000:
                print(f"  ⚠️  pdflatex had warnings but PDF was generated")
                return True
            print(f"  ❌ pdflatex failed:\n{result.stdout[-2000:]}")
            return False
    return True


def generate_agent_task(version: str, analysis_path: Path, results_dir: Path) -> str:
    """Generate the task description for the builder agent to write custom LaTeX."""
    
    # List available images
    images = sorted(results_dir.glob('*.png'))
    image_list = '\n'.join(f'  - {img.name}' for img in images)
    
    task = f"""You are building a LaTeX research report from experiment analysis results.

## Context
- Pipeline: {version}
- Analysis document: {analysis_path}
- Results directory: {results_dir}
- Available images:
{image_list}

## Instructions

1. **Read the analysis document** at `{analysis_path}` thoroughly
2. **Write a professional LaTeX report** that includes:
   - Title page with pipeline metadata
   - Table of contents
   - Executive summary with key findings
   - Detailed results tables (use booktabs for clean formatting)
   - All available plots embedded as figures with proper captions and references
   - Statistical analysis section with interpretation
   - Conclusions and recommendations for next steps
   - Appendix with raw data tables if useful

3. **Run any additional analysis scripts** you think would strengthen the report:
   - Bootstrap confidence intervals on top experiments
   - Per-fold breakdown for the top 3 experiments
   - Any statistical tests not in the analysis MD

4. **Save the LaTeX source** to `{results_dir}/{version}_report.tex`

5. **Compile to PDF** using:
   ```bash
   cd {results_dir}
   pdflatex -interaction=nonstopmode {version}_report.tex
   pdflatex -interaction=nonstopmode {version}_report.tex  # Second pass for TOC
   ```

6. **Verify the PDF** was created: `{results_dir}/{version}_report.pdf`

## Style Guide
- Use the article document class with 11pt font
- Use booktabs for tables (\\toprule, \\midrule, \\bottomrule)
- Use float [H] for figure placement
- Use \\textwidth for full-width figures, 0.48\\textwidth for side-by-side
- Include a \\tableofcontents after the title page
- Number sections
- Use hyperref for clickable TOC and cross-references
- Color scheme: dark blue (#2C3E50) for titles, teal (#16A085) for accents

## Quality Checklist
- [ ] All images referenced actually exist in the results directory
- [ ] Tables render correctly (check column alignment)
- [ ] PDF compiles without errors
- [ ] Page numbers and headers work
- [ ] Cross-references resolve (no '??' in output)
"""
    return task


def main():
    parser = argparse.ArgumentParser(description='Build LaTeX report from experiment analysis')
    parser.add_argument('version', help='Pipeline version')
    parser.add_argument('--agent', action='store_true', help='Use builder agent to write custom LaTeX')
    parser.add_argument('--compile-only', action='store_true', help='Just compile existing .tex file')
    parser.add_argument('--template', default=None, help='Custom LaTeX template path')
    args = parser.parse_args()
    
    version = args.version
    print(f"\n{'═' * 70}")
    print(f"  📄 REPORT BUILDER — {version}")
    print(f"  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"{'═' * 70}\n")
    
    results_dir = get_results_dir(version)
    print(f"  📂 Results: {results_dir}")
    
    if args.compile_only:
        tex_path = results_dir / f'{version}_report.tex'
        if not tex_path.exists():
            print(f"❌ No .tex file found: {tex_path}")
            sys.exit(1)
        success = build_with_pdflatex(tex_path, results_dir)
        if success:
            pdf_path = results_dir / f'{version}_report.pdf'
            print(f"\n  ✅ PDF compiled: {pdf_path}")
        sys.exit(0 if success else 1)
    
    # Find analysis markdown
    analysis_path = find_analysis_md(version, results_dir)
    if analysis_path is None:
        print(f"❌ No analysis markdown found.")
        print(f"   Run first: python3 scripts/analyze_local_results.py {version}")
        sys.exit(1)
    
    print(f"  📝 Analysis: {analysis_path.name}")
    
    if args.agent:
        # Generate task for builder agent and print it
        task = generate_agent_task(version, analysis_path, results_dir)
        task_path = results_dir / f'{version}_report_task.md'
        task_path.write_text(task)
        print(f"\n  📋 Agent task written to: {task_path}")
        print(f"  🤖 To spawn builder: use this task with reasoning enabled")
        print(task)
        sys.exit(0)
    
    # Auto mode: pandoc MD → PDF
    output_pdf = results_dir / f'{version}_report.pdf'
    template_path = Path(args.template) if args.template else None
    
    success = build_with_pandoc(analysis_path, output_pdf, results_dir, template_path)
    
    if success and output_pdf.exists():
        size_kb = output_pdf.stat().st_size / 1024
        print(f"\n  ✅ PDF report: {output_pdf}")
        print(f"  📊 Size: {size_kb:.1f} KB")
    else:
        print(f"\n  ⚠️  Pandoc conversion failed. Trying direct pdflatex fallback...")
        # Try to at least generate the .tex file via pandoc --to latex
        tex_path = results_dir / f'{version}_report.tex'
        fm, body = extract_frontmatter(analysis_path)
        clean_md = results_dir / f'{analysis_path.stem}_clean.md'
        clean_md.write_text(body)
        
        result = subprocess.run(
            ['pandoc', str(clean_md), '-o', str(tex_path), '--standalone',
             '-V', f'title={fm.get("title", version)}',
             '-V', f'date={fm.get("date", "")}',
             f'--resource-path={results_dir}'],
            capture_output=True, text=True, cwd=str(results_dir),
        )
        clean_md.unlink(missing_ok=True)
        
        if tex_path.exists():
            print(f"  📄 LaTeX source: {tex_path}")
            success = build_with_pdflatex(tex_path, results_dir)
            if success:
                pdf_path = results_dir / f'{version}_report.pdf'
                if pdf_path.exists():
                    print(f"  ✅ PDF compiled: {pdf_path}")
                    sys.exit(0)
        
        print(f"  ❌ All compilation methods failed.")
        print(f"  💡 Try: python3 scripts/build_report.py {version} --agent")
        sys.exit(1)
    
    print(f"\n{'═' * 70}")
    print(f"  ✅ REPORT COMPLETE — {version}")
    print(f"{'═' * 70}\n")


if __name__ == '__main__':
    main()
